/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaomi_chatbot_services_faiss_model_FaissJNI */

#ifndef _Included_com_xiaomi_chatbot_services_faiss_model_FaissJNI
#define _Included_com_xiaomi_chatbot_services_faiss_model_FaissJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    cppCtor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_cppCtor
(JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    is_trained
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_is_1trained
        (JNIEnv *, jobject);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    train
 * Signature: (I[F)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_train
(JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    add
 * Signature: (I[F)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_add
(JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    addWithIds
 * Signature: (I[F[J)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_addWithIds
(JNIEnv *, jobject, jint, jfloatArray, jlongArray);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    search
 * Signature: (I[FI[F[J)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_search
(JNIEnv *, jobject, jint, jfloatArray, jint, jfloatArray, jlongArray);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    assign
 * Signature: (I[F[II)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_assign
(JNIEnv *, jobject, jint, jfloatArray, jintArray, jint);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_reset
(JNIEnv *, jobject);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    reconstruct
 * Signature: (I[F)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_reconstruct
(JNIEnv *, jobject, jint, jfloatArray);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    reconstruct_n
 * Signature: (II[F)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_reconstruct_1n
(JNIEnv *, jobject, jint, jint, jfloatArray);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    display
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_display
(JNIEnv *, jobject);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    compute_residual
 * Signature: ([F[F)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_compute_1residual
(JNIEnv *, jobject, jfloatArray, jfloatArray);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    get_typename
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_get_1typename
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif