/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaomi_chatbot_services_faiss_model_FaissJNI */

#ifndef _Included_com_xiaomi_chatbot_services_faiss_model_FaissJNI
#define _Included_com_xiaomi_chatbot_services_faiss_model_FaissJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    cppCtor
 * Signature: (Ljava/lang/String;ILjava/util/Map;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_cppCtor
  (JNIEnv *, jobject, jstring, jint, jobject, jobject);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    isTrained
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_isTrained
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    train
 * Signature: (Ljava/lang/String;I[F)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_train
  (JNIEnv *, jobject, jstring, jint, jfloatArray);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    add
 * Signature: (Ljava/lang/String;I[F)I
 */
JNIEXPORT jint JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_add
  (JNIEnv *, jobject, jstring, jint, jfloatArray);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    addWithIds
 * Signature: (Ljava/lang/String;I[F[J)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_addWithIds
  (JNIEnv *, jobject, jstring, jint, jfloatArray, jlongArray);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    search
 * Signature: (Ljava/lang/String;I[FI[F[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_search
  (JNIEnv *, jobject, jstring, jint, jfloatArray, jint, jfloatArray, jobjectArray);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    assign
 * Signature: (Ljava/lang/String;I[F[II)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_assign
  (JNIEnv *, jobject, jstring, jint, jfloatArray, jintArray, jint);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    reset
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_reset
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    reconstruct
 * Signature: (Ljava/lang/String;I[F)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_reconstruct
  (JNIEnv *, jobject, jstring, jint, jfloatArray);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    reconstruct_n
 * Signature: (Ljava/lang/String;II[F)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_reconstruct_1n
  (JNIEnv *, jobject, jstring, jint, jint, jfloatArray);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    display
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_display
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    compute_residual
 * Signature: (Ljava/lang/String;[F[F)V
 */
JNIEXPORT void JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_compute_1residual
  (JNIEnv *, jobject, jstring, jfloatArray, jfloatArray);

/*
 * Class:     com_xiaomi_chatbot_services_faiss_model_FaissJNI
 * Method:    get_typename
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xiaomi_chatbot_services_faiss_model_FaissJNI_get_1typename
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
